language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -e .
  - pip install nose rednose coverage coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
script:
  - nosetests --with-coverage
after_success:
  - coveralls --rcfile=coverage.rc
